const char *vertexshader=
"#version 330 core\n"
"layout (location=0) in vec2 pos;\n"
"layout (location=1) in vec2 tc;\n"
"layout (location=2) in vec2 xy;\n"
"layout (location=3) in float rot;\n"
"layout (location=4) in float tex_coord_offset;\n"
"out vec2 texcoord;\n"
"uniform mat4 projection;\n"
"uniform float size;\n"
"void main(){\n"
"mat4 translate = mat4(1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, xy.x + (size / 2.0), xy.y + (size / 2.0), 0.0, 1.0);\n"
"mat4 rotate = mat4(cos(rot), sin(rot), 0.0, 0.0, -sin(rot), cos(rot), 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0);\n"
"texcoord = vec2(tc.x + tex_coord_offset, tc.y);\n"
"gl_Position = projection * translate * rotate * vec4(pos.x * size, pos.y * size, 0.0, 1.0);\n"
"}\n"
,*fragmentshader=
"#version 330 core\n"
"out vec4 color;\n"
"in vec2 texcoord;\n"
"uniform sampler2D tex;\n"
"void main(){\n"
"color = texture(tex, texcoord);\n"
"}\n"
;
